### ISSUE TITLE
Enabling touch disables link clicks

### ISSUE THREAD

**Issue by izkara** [guins/jQuery.scrollSections#18]
Great Plugin! Really easy to implement. My only issue right now is that when I look at my website on my phone the scrolling works but I can't tap on any links to open them, rendering them useless. Any advice?

**Comment by sandrodz** [comment]
Hey, I used to have the same issue. But I don't remember how I fixed it... I'll dig into it maybe I can remember.

p.s. check out my fork, it has some fixes.

**Comment by izkara** [comment]
Hi Sandrodz,

Thanks for replying! I actually already have your version [4.4] in my code, and I'm still running into the same problem. Although touch works with the scroll, which it hadn't before, it still doesn't let me click links or anything.

Hope we can figure this out!

**Comment by izkara** [comment]
Hey anybody,

I've sort of figured out where the problem lies. In the build in the code controlling the touch responses, the last return false statement in there is what shuts off clicking. I see there is a portion of code looking at the speed of a touch movement- I'm trying to get it to detect when the touch is a tap vs when it is a swipe, and if it is a tap then do not return false, and if it is a swipe then do return false.

I'm very new to javascript. Anyone who can help?
